(function() {var implementors = {};
implementors["modio"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"modio/auth/enum.Credentials.html\" title=\"enum modio::auth::Credentials\">Credentials</a>",synthetic:false,types:["modio::auth::Credentials"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"modio/filter/enum.Operator.html\" title=\"enum modio::filter::Operator\">Operator</a>",synthetic:false,types:["modio::filter::Operator"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"modio/mods/enum.Rating.html\" title=\"enum modio::mods::Rating\">Rating</a>",synthetic:false,types:["modio::mods::Rating"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"modio/teams/enum.TeamLevel.html\" title=\"enum modio::teams::TeamLevel\">TeamLevel</a>",synthetic:false,types:["modio::types::mods::TeamLevel"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"enum\" href=\"modio/users/enum.Resource.html\" title=\"enum modio::users::Resource\">Resource</a>",synthetic:false,types:["modio::users::Resource"]},{text:"impl&lt;C:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"modio/struct.Modio.html\" title=\"struct modio::Modio\">Modio</a>&lt;C&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;C: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"https://docs.rs/hyper/0.12.13/hyper/client/connect/trait.Connect.html\" title=\"trait hyper::client::connect::Connect\">Connect</a> + 'static,&nbsp;</span>",synthetic:false,types:["modio::Modio"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
