name: docs

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  docs:
    name: Deploy docs to gh-pages
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Generate docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --all-features

      - name: Prepare docs
        shell: bash -e -O extglob {0}
        run: |
          DIR=${GITHUB_REF/refs\/+(heads|tags)\//}
          mkdir -p ./docs/$DIR
          touch ./docs/.nojekyll
          echo '<meta http-equiv="refresh" content="0;url=modio/index.html">' > ./docs/$DIR/index.html
          mv ./target/doc/* ./docs/$DIR/

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./docs
          allow_empty_commit: false
          keep_files: true
